modName=DynamicTreesIceAndFireAddon
modId=dticeandfire_addon
modVersion=1.0.1
group=groupix05.dticeandfire_addon
AuthorName=Groupix05

mcVersion=1.20.1
forgeVersion=47.4.8
mappingsVersion=2023.09.03

dynamicTreesVersion=1.4.5
dynamicTreesPlusVersion=1.2.0-BETA2

curseFileType=release

org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
