license="MIT"
modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Groupix05/DynamicTrees-Generator/issues"

[[mods]]
modId="dticeandfire_addon"
version="${file.jarVersion}"
displayName="Dynamic Trees for Ice and Fire: Addon"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamictrees"
logoFile="logo.png"
credits=""
authors="Groupix05"
description='''
Adds Dynamic Trees compatibility for Ice and Fire: Addon
'''

[[dependencies.dticeandfire_addon]]
    modId="forge"
    mandatory=true
    versionRange="[47.3.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dticeandfire_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dticeandfire_addon]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.4.5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dticeandfire_addon]]
    modId="iceandaddon"
    mandatory=true
    versionRange="[0.0.5,)"
    ordering="AFTER"
    side="BOTH"
